# Header
menu:
  Home: /
  Archives: /archives
rss: /atom.xml

# Content
excerpt_link: Leia mais
fancybox: true

# Sidebar
sidebar: right
widgets:
- category
- tag
- tagcloud
#- archive
#- recent_posts

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
 - category
# - tagcloud
# - archive

# widget behavior
archive_type: 'monthly'
show_count: false

# Miscellaneous
google_analytics: UA-83746351-2
gauges_analytics: 5d3cf2743a586c64c83002bb
favicon: /favicon.png
twitter:
google_plus:
fb_admins:
fb_app_id:
